project:
  type: book

book:
  title: "An Introduction to Single Cell RNAseq with Seurat"
  author: "Norah Jones"
  date: "9/25/2025"
  chapters:
    - index.qmd
    - Intro.qmd

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



